function PluginPanel({scope}) {
 const e=React.createElement,snapshot=useFileConfig(scope),[state,setState]=React.useState(null),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[review,setReview]=React.useState(null);
 const alive=React.useRef(false),working=React.useRef(false),timer=React.useRef(null),epoch=React.useRef(0),serial=React.useRef(0);
 const reload=async()=>{const version=epoch.current,sequence=++serial.current,value=await scope.call('status',{});if(alive.current&&version===epoch.current&&sequence===serial.current){setState(value);setReview(current=>{if(!current)return null;const row=value.recovery?.find(row=>row.id===current.id);return row?{...current,...row}:null;});clearTimeout(timer.current);if(value.busy||value.vectorBusy)timer.current=setTimeout(()=>{if(document.visibilityState!=='hidden')void reload().catch(reason=>{if(alive.current&&version===epoch.current)setError(reason.message);});},2000);}return value;};
 React.useEffect(()=>{alive.current=true;const version=++epoch.current;setState(null);setError('');setReview(null);const refresh=()=>{clearTimeout(timer.current);if(document.visibilityState!=='hidden'&&snapshot.status==='ready'&&snapshot.value.enabled)void reload().catch(reason=>{if(alive.current&&version===epoch.current)setError(reason.message);});};refresh();window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{alive.current=false;++epoch.current;clearTimeout(timer.current);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[scope,snapshot.revision]);
 const work=async(fn)=>{if(working.current)return;const version=epoch.current;working.current=true;setBusy(true);setError('');try{await fn();if(alive.current&&version===epoch.current)await reload();}catch(reason){if(alive.current&&version===epoch.current)setError(reason.message);}finally{working.current=false;if(alive.current)setBusy(false);}};
 const button=(label,fn,variant='outline',disabled=false)=>e(DshButton,{type:'button',variant,disabled:busy||!snapshot.writable||disabled,onClick:()=>void work(fn)},label);
 const start=kind=>scope.call('startMemory',{kind});
 const source=item=>e('details',{key:item.sessionId+':'+item.seq},e('summary',null,item.sessionId+' #'+item.seq),e('blockquote',null,item.quote));
 const pending=state?.candidates.filter(item=>item.state==='pending')??[],promoted=state?.candidates.filter(item=>item.state==='promoted')??[];
 return e('section',{className:'dpc-page memory-panel','aria-label':'Dream 与长期记忆'},
  e('style',null,'.memory-panel{margin-bottom:32px}.memory-toolbar{display:flex;gap:10px;flex-wrap:wrap}.memory-item{padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;margin:12px 0}.memory-item p{margin:6px 0}.memory-meta{font-size:12px;color:var(--dsw-alias-label-tertiary)}.memory-panel blockquote{border-left:3px solid var(--dsw-alias-border-l2);padding-left:12px;margin:10px 0;white-space:pre-wrap}.memory-panel table{width:100%;font-size:12px;border-collapse:collapse}.memory-panel td,.memory-panel th{text-align:left;padding:9px;border-bottom:1px solid var(--dsw-alias-border-l2)}.memory-panel code{overflow-wrap:anywhere}'),
  e('div',{className:'memory-toolbar'},button('整理今日记忆',()=>start('daily'),'outline',!!state?.busy),button('Dream 整理',()=>start('dream'),'primary',!!state?.busy),button('复查本周',()=>start('weekly'),'outline',!!state?.busy),state?.busy||state?.vectorBusy?button('取消整理',()=>scope.call('cancel',{})):null),
  error?e('p',{role:'alert'},error):null,state?.scheduleError?e('p',{role:'alert'},'自动任务：'+state.scheduleError):null,state?.workflowError?e('p',{role:'alert'},state.workflowError):null,
  !state?e('p',null,'正在读取记忆状态…'):e(React.Fragment,null,e('p',{className:'memory-meta'},'当前工作区：',e('code',null,state.workspace)),state.busy?e('p',{role:'status'},'正在整理。会使用配置的模型；结果保留在本页的运行记录中。'):null,
   state.recovery?.length?e('section',{'aria-label':'记忆写入恢复'},e('p',{role:'alert'},'有写入需要核对。现有文件会保留，差异审阅后可以重新核对或放弃尚未提交的操作。'),state.recovery.map(row=>e('article',{className:'memory-item',key:row.id},e('p',null,row.file+' · '+row.preset+' · '+({report:'整理报告',promote:'记忆晋升',forget:'遗忘记忆'}[row.kind]??'记忆写入')),e('p',{className:'memory-meta'},row.committed?'记录已提交，暂存内容待核对':row.error??'另一进程正在提交'),button('查看恢复差异',async()=>{const version=epoch.current,value=await scope.call('inspectCommit',{id:row.id});if(alive.current&&version===epoch.current)setReview(value);}))),button('重新核对恢复',()=>scope.call('recheckCommits',{}))):null,
   state.vectorCleanup?e('section',{'aria-label':'向量清理状态'},e('p',{role:'status'},'有 '+state.vectorCleanup+' 项外部向量清理待完成；已遗忘事实不会继续被检索。'),button('重试向量清理',()=>scope.call('retryVectorCleanup',{}))):null,
   e('details',{open:true},e('summary',null,'候选记忆 · '+pending.length),pending.length?pending.map(item=>e('article',{className:'memory-item',key:item.id},e('p',null,item.text),e('p',{className:'memory-meta'},'可信度 '+Math.round(item.confidence*100)+'% · '+item.observations+' 个独立来源'+(item.expired?' · 已过期':'')+(item.conflict?' · 存在同主题冲突，请审阅后决定':'')),e('details',null,e('summary',null,'查看出处'),item.sources.map(source)),e('div',{className:'dpc-actions'},button(item.conflict?'确认更新记忆':'确认晋升',async()=>{if(window.confirm((item.conflict?'将替换同主题的受管记忆，请确认：':'加入 MEMORY.md，请确认：')+item.text))await scope.call('promote',{id:item.id,confirmation:item.id});},'primary',item.expired),button('遗忘候选',async()=>{if(window.confirm('遗忘这条候选及其来源？'))await scope.call('forget',{id:item.id});})))):e('p',null,'尚无待确认候选。整理会话后会显示有出处的稳定事实。')),
   e('details',null,e('summary',null,'已确认记忆 · '+promoted.length),promoted.map(item=>e('article',{className:'memory-item',key:item.id},e('p',null,item.text),item.reviewDue?e('p',{role:'status'},'此记忆已超过复核周期，暂不参与自动召回，请人工确认现状。'):null,e('p',{className:'memory-meta'},'生效：'+(item.validFrom?new Date(item.validFrom).toLocaleDateString():'旧版本')+(item.reviewedAt?' · 最近核验：'+new Date(item.reviewedAt).toLocaleDateString():'')),e('details',null,e('summary',null,'查看出处'),item.sources.map(source)),button('确认仍有效',async()=>{if(window.confirm('已人工核对这条事实目前仍然成立？'+item.text))await scope.call('reaffirm',{id:item.id,confirmation:item.id});},'outline'),button('遗忘记忆',async()=>{if(window.confirm('从 MEMORY.md 移除这条受管记忆并遗忘来源？'))await scope.call('forget',{id:item.id});})))),
   e('details',null,e('summary',null,'向量检索'),e('p',{className:'memory-meta'},'已注册提供方：'+(state.vectorProviders.join('、')||'暂未注册，使用词语检索')),e('p',{className:'memory-meta'},'可用存储：'+(state.vectorStores??['sqlite']).join('、')),snapshot.value.embeddingProvider?button(state.vectorBusy?'正在更新索引…':'重建向量索引',()=>scope.call('startRebuildVectors',{}),'outline',!!state.vectorBusy):null,state.vectorResult?e('p',{role:state.vectorResult.error?'alert':'status'},state.vectorResult.error??('已索引 '+state.vectorResult.indexed+' 条，更新 '+state.vectorResult.updated+' 条')):null),
   e('details',null,e('summary',null,'自动任务与执行记录'),
    button('核对自动任务记录',()=>scope.call('recheckWorkflows',{})),
    e('p',{className:'memory-meta'},'核对原生会话与投递记录，保留已提交产物；中断的模型作业需审阅后手动整理。'),
    state.schedules.map(task=>e('p',{className:'memory-meta',key:task.id},task.title+' · '+task.status+' · 下一次 '+new Date(task.scheduledAt).toLocaleString())),
    (state.templates??[]).map(row=>e('article',{className:'memory-item',key:row.id},e('p',null,({daily:'每日记忆',dream:'Dream',weekly:'每周复查'}[row.kind]??row.kind)+' · '+({ready:'计划已就绪',new:'待创建',creating:'创建待核对',updating:'修改待核对',deleting:'删除待核对',removed:'计划已移除','needs-review':'计划需核对'}[row.state]??row.state)),row.note?e('p',{role:'status'},row.note):null,row.historyIncomplete?e('p',{className:'memory-meta'},'原生投递历史部分不可用；已保存 '+row.receipts+' 条摘要，执行结果仍以原生会话和产物为依据。'):null)),
    (state.workflows??[]).length?e('section',{'aria-label':'自动任务执行账本'},e('h4',null,'原生轮次'),(state.workflows??[]).map(row=>e('article',{className:'memory-item',key:row.id},e('p',null,({daily:'每日记忆',dream:'Dream',weekly:'每周复查'}[row.kind]??row.kind)+' · '+({delivered:'已投递，等待执行',running:'运行中','awaiting-user':'等待你的回答','awaiting-approval':'等待原生审批',completed:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断','needs-review':'需核对'}[row.state]??row.state)),e('p',{className:'memory-meta'},'计划时间：'+new Date(row.occurrence).toLocaleString()),row.note?e('p',{role:'status'},row.note):null,(row.result?.artifacts??[]).map(artifact=>e('p',{key:artifact.path},artifact.path))))):null,
    e('h4',null,'记忆作业'),e('table',null,e('thead',null,e('tr',null,e('th',null,'任务'),e('th',null,'状态'),e('th',null,'时间 / 产物'))),e('tbody',null,state.runs.map(run=>e('tr',{key:run.id},e('td',null,{daily:'每日记忆',dream:'Dream',weekly:'每周复查'}[run.kind]??run.kind),e('td',null,{completed:'已完成',running:'执行中',failed:'失败',cancelled:'已取消',interrupted:'已中断'}[run.state]??run.state),e('td',null,new Date(run.started).toLocaleString(),run.result?.error?e('p',{role:run.state==='failed'?'alert':'status'},run.state==='cancelled'?'已取消本次整理。':run.result.error):null,(run.result?.artifacts??[]).map(artifact=>e('p',{key:artifact.path},artifact.path)),run.result?.empty?e('p',null,'没有新材料'):null,run.result?.deduplicated?e('p',null,'材料未变，已复用结果'):null)))))),
  ),
  review?e('section',{'aria-label':'记忆恢复差异'},
   e('h4',null,review.file+' · 恢复审阅'),
   [['before','写入前'],['after','本次预期内容'],['current','当前文件']].map(([key,label])=>e('details',{key,open:key==='current'},
    e('summary',null,label),e('pre',{style:{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:360,overflow:'auto'}},review[key]??'（文件不存在）')
   )),
   e('div',{className:'dpc-actions'},!review.committed?button('保留当前文件并放弃操作',async()=>{
    if(window.confirm('保留当前文件，放弃这次尚未提交的记忆操作？候选记录不会按这次操作更新。')){await scope.call('discardCommit',{id:review.id,confirmation:review.id});setReview(null);}
   }):null,button('关闭恢复审阅',async()=>setReview(null)))
  ):null,
  e('p',{className:'memory-meta'},'Daily 写入 memory/日期.md，Dream 写入 DREAMS.md；确认后的事实写入 MEMORY.md。人工内容会保留。'),
 );
}
